# Generated by Django 3.2.6 on 2023-02-17 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=200, null=True, verbose_name='Jméno')),
                ('prijmeni', models.CharField(max_length=180, null=True, verbose_name='Příjmení')),
                ('rodne_cislo', models.CharField(max_length=200, null=True, verbose_name='Rodné číslo')),
                ('ulice', models.CharField(max_length=180, null=True, verbose_name='Ulice')),
                ('cislo_popisne', models.CharField(max_length=15, null=True, verbose_name='Číslo popisné')),
                ('psc', models.CharField(max_length=6, null=True, verbose_name='PSČ')),
                ('mesto', models.CharField(max_length=120, null=True, verbose_name='Město')),
                ('e_mail', models.EmailField(max_length=120, null=True, verbose_name='E-mail')),
                ('telefon', models.CharField(max_length=15, null=True, verbose_name='Telefon')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Datum registrace')),
            ],
            options={
                'verbose_name': 'Klient',
                'verbose_name_plural': 'Klienti',
            },
        ),
        migrations.CreateModel(
            name='Produkty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_produktu', models.CharField(choices=[('pojištění majetku', 'Pojištění majetku'), ('úrazové pojištění', 'Úrazové pojištění'), ('cestovní pojištění', 'Cestovní pojištění')], default='Pojištění majetku', max_length=80)),
                ('castka', models.PositiveIntegerField(verbose_name='Částka')),
                ('predmet', models.CharField(max_length=80, verbose_name='Předmět produktu')),
                ('platnost_od', models.CharField(max_length=20, verbose_name='Platnost od')),
                ('platnost_do', models.CharField(max_length=20, verbose_name='Platnost do')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Datum registrace')),
                ('status', models.CharField(choices=[('návrh', 'Návrh'), ('uzavřena', 'Uzavřena'), ('zrušena', 'Zrušena')], max_length=32, null=True, verbose_name='Status')),
                ('klient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evidence_pojisteni.klient')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
            },
        ),
    ]
