# Generated by Django 3.2.6 on 2023-02-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='status',
            field=models.CharField(choices=[('návrh', 'Návrh'), ('aktivní', 'Aktivní'), ('neaktivní', 'Neaktivní')], max_length=32, null=True, verbose_name='Status'),
        ),
    ]
