# Generated by Django 3.2.6 on 2023-02-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0002_alter_produkty_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='e_mail',
            field=models.EmailField(max_length=120, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='klient',
            name='rodne_cislo',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Rodné číslo'),
        ),
        migrations.AlterField(
            model_name='klient',
            name='telefon',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='Telefon'),
        ),
    ]
