# Generated by Django 3.2.6 on 2023-02-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0003_auto_20230217_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkty',
            name='doba_trvani',
            field=models.CharField(choices=[('1 rok', '1 rok'), ('2 roky', '2 roky'), ('Na neurčito', 'na neurčito')], max_length=80, null=True, verbose_name='Doba trvání'),
        ),
        migrations.AlterField(
            model_name='produkty',
            name='castka',
            field=models.PositiveIntegerField(null=True, verbose_name='Částka'),
        ),
        migrations.AlterField(
            model_name='produkty',
            name='nazev_produktu',
            field=models.CharField(choices=[('pojištění majetku', 'Pojištění majetku'), ('úrazové pojištění', 'Úrazové pojištění'), ('cestovní pojištění', 'Cestovní pojištění')], max_length=80, null=True, verbose_name='Název produktu'),
        ),
        migrations.AlterField(
            model_name='produkty',
            name='platnost_do',
            field=models.CharField(max_length=20, null=True, verbose_name='Platnost do'),
        ),
        migrations.AlterField(
            model_name='produkty',
            name='platnost_od',
            field=models.CharField(max_length=20, null=True, verbose_name='Platnost od'),
        ),
        migrations.AlterField(
            model_name='produkty',
            name='predmet',
            field=models.CharField(max_length=80, null=True, verbose_name='Předmět produktu'),
        ),
    ]
