# Generated by Django 3.2.6 on 2023-02-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0004_auto_20230218_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='doba_trvani',
            field=models.CharField(choices=[('1 rok', '1 rok'), ('2 roky', '2 roky'), ('Na neurčito', 'na neurčito')], max_length=80, null=True, verbose_name='Doba trvání smlouvy'),
        ),
    ]
