# Generated by Django 3.2.6 on 2023-02-18 15:58

from django.db import migrations, models
import evidence_pojisteni.models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0005_alter_produkty_doba_trvani'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='psc',
            field=models.CharField(max_length=5, null=True, validators=[evidence_pojisteni.models.only_int], verbose_name='PSČ'),
        ),
    ]
