# Generated by Django 3.2.6 on 2023-02-18 16:15

from django.db import migrations, models
import evidence_pojisteni.models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0006_alter_klient_psc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='psc',
            field=models.CharField(max_length=5, null=True, validators=[evidence_pojisteni.models.psc], verbose_name='PSČ'),
        ),
        migrations.AlterField(
            model_name='klient',
            name='rodne_cislo',
            field=models.CharField(max_length=200, null=True, unique=True, validators=[evidence_pojisteni.models.only_int], verbose_name='Rodné číslo'),
        ),
        migrations.AlterField(
            model_name='klient',
            name='telefon',
            field=models.CharField(max_length=9, null=True, unique=True, validators=[evidence_pojisteni.models.only_int], verbose_name='Telefon'),
        ),
    ]
