# Generated by Django 3.2.6 on 2023-02-18 16:29

from django.db import migrations, models
import evidence_pojisteni.models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0007_auto_20230218_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='rodne_cislo',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[evidence_pojisteni.models.only_int], verbose_name='Rodné číslo'),
        ),
        migrations.AlterField(
            model_name='klient',
            name='telefon',
            field=models.CharField(max_length=9, null=True, unique=True, validators=[evidence_pojisteni.models.telefon], verbose_name='Telefon'),
        ),
    ]
