# Generated by Django 3.2.6 on 2023-02-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0008_auto_20230218_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='status',
            field=models.CharField(choices=[('aktivní', 'Aktivní'), ('neaktivní', 'Neaktivní')], max_length=32, null=True, verbose_name='Status'),
        ),
    ]
