# Generated by Django 3.2.6 on 2023-02-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0009_alter_produkty_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='nazev_produktu',
            field=models.CharField(choices=[('Pojištění majetku', 'Pojištění majetku'), ('Úrazové pojištění', 'Úrazové pojištění'), ('Cestovní pojištění', 'Cestovní pojištění')], max_length=80, null=True, verbose_name='Název produktu'),
        ),
    ]
