# Generated by Django 3.2.6 on 2023-02-18 20:46

from django.db import migrations, models
import evidence_pojisteni.models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0010_alter_produkty_nazev_produktu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='rodne_cislo',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[evidence_pojisteni.models.rodne_cislo], verbose_name='Rodné číslo'),
        ),
        migrations.AlterField(
            model_name='produkty',
            name='castka',
            field=models.CharField(max_length=50, null=True, validators=[evidence_pojisteni.models.only_int], verbose_name='Částka'),
        ),
    ]
