# Generated by Django 3.2.6 on 2023-02-18 21:02

from django.db import migrations, models
import evidence_pojisteni.models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0011_auto_20230218_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='castka',
            field=models.CharField(max_length=10, null=True, validators=[evidence_pojisteni.models.only_int], verbose_name='Částka'),
        ),
    ]
