# Generated by Django 3.2.6 on 2023-02-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0012_alter_produkty_castka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='status',
            field=models.CharField(choices=[('aktivní', 'Aktivní'), ('neaktivní', 'Neaktivní')], default='aktivni', max_length=32, null=True, verbose_name='Status'),
        ),
    ]
