# Generated by Django 3.2.6 on 2023-02-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0013_alter_produkty_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkty',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
