# Generated by Django 3.2.6 on 2023-02-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0015_remove_produkty_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkty',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='produkty',
            name='platnost_od',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Datum registrace'),
        ),
    ]
