# Generated by Django 3.2.6 on 2023-02-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni', '0016_auto_20230220_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkty',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Datum registrace'),
        ),
        migrations.AlterField(
            model_name='produkty',
            name='platnost_od',
            field=models.CharField(max_length=20, null=True, verbose_name='Platnost od'),
        ),
    ]
